apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: todos-proxy
spec:
  virtualhost:
    fqdn: todos.test.tanzutime.com
    tls: 
      secretName: httpproxy-tls
  routes:
  - services:
    - name: todo-ui
      port: 80
    conditions:
      - prefix: /
    requestHeadersPolicy:
      set:
      - name: Host
        value: todo-ui-demos.apps.taptest.tanzutime.com
  - services:
    - name: todo-service
      port: 80
    conditions:
      - prefix: /api
    requestHeadersPolicy:
      set:
      - name: Host
        value: todo-service-demos.apps.taptest.tanzutime.com
