apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: todo-service
  annotations:
    "backstage.io/kubernetes-label-selector": "app.kubernetes.io/part-of=todo-service"
spec:
  type: service
  lifecycle: experimental
  owner: default-owner
