apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: todo-service
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: todo-service
spec:
  source:
    git:
      url: https://github.com/odedia/todo-service
      ref:
        branch: main
