apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: todo-service-local
  labels:
    apps.tanzu.vmware.com/workload-type: web
spec:
  serviceClaims:
  - name: rmq
    ref:
      apiVersion: rabbitmq.com/v1beta1
      kind: RabbitmqCluster
      name: rmq-1
  # env:
  #   - name: SPRING_PROFILES_ACTIVE
  #     value: default
  # params:
    # - name: run-image
    #   value: harbor.apps.cf.tanzutime.com/apps/todo-service-local
    # - name: tekton-pipeline-name
    #   value: developer-defined-tekton-pipeline
  source:
    git:
      url: https://github.com/odedia/todo-service
      ref:
        branch: tap
