apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: todo-service
  labels:
    apps.tanzu.vmware.com/workload-type: web-test
spec:
  serviceClaims:
  - name: mysql
    ref:
      apiVersion: with.sql.tanzu.vmware.com/v1
      kind: MySQL
      name: mysql
  params:
    - name: run-image
      value: harbor.apps.cf.tanzutime.com/apps/todo-service
  source:
    git:
      url: https://github.com/odedia/todo-service
      ref:
        branch: tap
